### ISSUE TITLE
Anteproyecto

### ISSUE THREAD

**Issue by Gonzalo-Garcia-C** [fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-tp_labo#1]
Subo el pdf del anteproyecto.
Saludos

https://github.com/fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-tp_labo/blob/master/doc/anteproyecto/Anteproyecto.pdf

**Comment by rarias** [comment]
ok, recibido.
Vamos a ir mejorando este documento, que luego será el informe del proyecto.
Slds
