### ISSUE TITLE
Código lcd 

### ISSUE THREAD

**Issue by Gonzalo-Garcia-C** [fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-tp_labo#3]
Subo la primera versión del código para usar el dilplay lcd con I2C

https://github.com/fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-tp_labo/blob/master/codigo/LCD_I2C.asm

**Comment by rarias** [comment]
ok, podemos emprolijarlo un poco.
Agregá [https://github.com/fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-tp_labo/blob/master/codigo/LCD_I2C.asm](url) en la línea 24, a qué frecuencia funciona el micro.
